# Generated by Django 5.2.16 on 2026-07-23 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='gastos/', verbose_name='Foto del gasto')),
                ('deuda_50_50', models.DecimalField(decimal_places=2, editable=False, max_digits=8, verbose_name='Deuda 50/50')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('pagado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_pagados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=300, max_digits=8, verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha del pago')),
                ('comprobante_pdf', models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante PDF')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
