# Generated by Django 5.2.16 on 2026-07-25 09:55

import finanzas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='pagado_por',
        ),
        migrations.AddField(
            model_name='gasto',
            name='comprobante_pdf',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/gastos/', verbose_name='Comprobante PDF'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante_pdf',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', validators=[finanzas.models.validar_pdf], verbose_name='Comprobante PDF'),
        ),
    ]
