# Generated by Django 5.2.16 on 2026-08-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_remove_gasto_foto_remove_gasto_pagado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/gastos/', verbose_name='Foto del gasto'),
        ),
    ]
