# Generated by Django 5.2.16 on 2026-08-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_gasto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='comprobante_pdf',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='foto',
        ),
        migrations.AddField(
            model_name='gasto',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/gastos/', verbose_name='Comprobante'),
        ),
    ]
