# Generated by Django 5.2.16 on 2026-08-01 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_remove_gasto_comprobante_pdf_remove_gasto_foto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha del gasto'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='pagado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_pagados', to=settings.AUTH_USER_MODEL),
        ),
    ]
