# Generated by Django 5.2.16 on 2026-08-03 18:33

import django.db.models.deletion
import finanzas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_gasto_fecha_gasto_pagado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='comprobante_deuda',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/deuda/', validators=[finanzas.models.validar_pdf], verbose_name='Comprobante de deuda'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='deuda_pagada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deudas_pagadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gasto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('finiquitado', 'Finiquitado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
