# Generated by Django 5.2.16 on 2026-08-07 12:58

import django.db.models.deletion
from django.db import migrations, models


def rellenar_grupo(apps, schema_editor):
    """Pagos y gastos ya existentes: se asignan al grupo de quien los creó
    (vía su perfil de Padre) o, si no se puede determinar, al primer grupo."""
    Gasto = apps.get_model('finanzas', 'Gasto')
    Pago = apps.get_model('finanzas', 'Pago')
    Padre = apps.get_model('core', 'Padre')
    GrupoCoparental = apps.get_model('core', 'GrupoCoparental')

    primero = GrupoCoparental.objects.order_by('id').first()
    primero_id = primero.id if primero else None

    def grupo_de(user_id):
        if user_id:
            padre = Padre.objects.filter(user_id=user_id).first()
            if padre and padre.grupo_id:
                return padre.grupo_id
        return primero_id

    for gasto in Gasto.objects.filter(grupo__isnull=True):
        grupo_id = grupo_de(gasto.pagado_por_id)
        if grupo_id:
            gasto.grupo_id = grupo_id
            gasto.save(update_fields=['grupo'])

    for pago in Pago.objects.filter(grupo__isnull=True):
        grupo_id = grupo_de(pago.creado_por_id)
        if grupo_id:
            pago.grupo_id = grupo_id
            pago.save(update_fields=['grupo'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_canalrol_rol'),
        ('finanzas', '0006_gasto_comprobante_deuda_gasto_deuda_pagada_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='core.grupocoparental'),
        ),
        migrations.AddField(
            model_name='pago',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.grupocoparental'),
        ),
        migrations.RunPython(rellenar_grupo, noop),
    ]
