# Generated by Django 5.2.16 on 2026-08-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_canalrol_rol'),
        ('finanzas', '0007_gasto_grupo_pago_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='core.grupocoparental'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.grupocoparental'),
        ),
    ]
