# Generated by Django 5.2.16 on 2026-07-27 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grupocoparental_padre_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionCoparental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('aceptada', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='core.grupocoparental')),
            ],
        ),
    ]
