# Generated by Django 5.2.16 on 2026-07-29 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invitacioncoparental'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('medico', 'Médico'), ('psicologo', 'Psicólogo'), ('abogado', 'Abogado'), ('tutor', 'Tutor'), ('profesor', 'Profesor')], max_length=50)),
                ('autorizado_por_padre', models.BooleanField(default=False)),
                ('autorizado_por_madre', models.BooleanField(default=False)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externos', to='core.grupocoparental')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
