# Generated by Django 5.2.16 on 2026-08-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_miembroexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='padre',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='padre',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de perfil'),
        ),
    ]
