# Generated by Django 5.2.16 on 2026-08-05 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_padre_fecha_nacimiento_padre_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembroexterno',
            name='rol',
            field=models.CharField(choices=[('medico', 'Médico'), ('psicologo', 'Psicólogo'), ('abogado', 'Abogado'), ('dentista', 'Dentista'), ('asistenta_social', 'Asistenta social'), ('profesor', 'Profesor'), ('tutor', 'Tutor legal')], max_length=50),
        ),
        migrations.CreateModel(
            name='CanalRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('medico', 'Médico'), ('psicologo', 'Psicólogo'), ('abogado', 'Abogado'), ('dentista', 'Dentista'), ('asistenta_social', 'Asistenta social'), ('profesor', 'Profesor'), ('tutor', 'Tutor legal')], max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canales', to='core.grupocoparental')),
            ],
            options={
                'unique_together': {('grupo', 'rol')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='canales/documentos/%Y/%m/', verbose_name='Archivo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.canalrol')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_canal_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='InvitacionExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('rol', models.CharField(choices=[('medico', 'Médico'), ('psicologo', 'Psicólogo'), ('abogado', 'Abogado'), ('dentista', 'Dentista'), ('asistenta_social', 'Asistenta social'), ('profesor', 'Profesor'), ('tutor', 'Tutor legal')], max_length=50)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('aceptada', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_externos', to='core.grupocoparental')),
                ('invitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_externos_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_canal', to=settings.AUTH_USER_MODEL)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.canalrol')),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
