# Generated by Django 5.2.16 on 2026-08-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_miembroexterno_rol_canalrol_documentocanal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canalrol',
            name='rol',
            field=models.CharField(choices=[('medico', 'Médico'), ('psicologo', 'Psicólogo'), ('abogado', 'Abogado'), ('dentista', 'Dentista'), ('asistenta_social', 'Asistenta social'), ('profesor', 'Profesor'), ('tutor', 'Tutor legal'), ('general', 'General / Otros')], max_length=50),
        ),
    ]
