# Generated by Django 5.2.16 on 2026-09-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_canalrol_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='padre',
            name='notificaciones_email',
            field=models.BooleanField(default=True, verbose_name='Recibir notificaciones por email'),
        ),
    ]
