# Generated by Django 5.2.16 on 2026-07-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('visita', 'Visita'), ('vacacion', 'Vacación')], max_length=20, verbose_name='Tipo de evento')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('punto_encuentro', models.CharField(choices=[('igualada', 'Igualada'), ('cervera_estacion', 'Estación de Cervera'), ('montblanc_ap2', 'Montblanc AP-2')], max_length=50, verbose_name='Punto de encuentro')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
        ),
    ]
