# Generated by Django 5.2.16 on 2026-08-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('visita', 'Visita'), ('vacacion', 'Vacaciones')], max_length=20, verbose_name='Tipo de evento'),
        ),
    ]
