# Generated by Django 5.2.16 on 2026-08-07 12:58

import django.db.models.deletion
from django.db import migrations, models


def rellenar_grupo(apps, schema_editor):
    """Los eventos ya existentes se crearon antes de que hubiera más de un
    grupo coparental: se asignan todos al primer (y hasta ahora único) grupo."""
    Evento = apps.get_model('calendario', 'Evento')
    GrupoCoparental = apps.get_model('core', 'GrupoCoparental')
    primero = GrupoCoparental.objects.order_by('id').first()
    if primero:
        Evento.objects.filter(grupo__isnull=True).update(grupo_id=primero.id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_alter_evento_tipo'),
        ('core', '0008_alter_canalrol_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.grupocoparental'),
        ),
        migrations.RunPython(rellenar_grupo, noop),
    ]
