# Generated by Django 5.2.16 on 2026-08-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_evento_grupo'),
        ('core', '0008_alter_canalrol_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.grupocoparental'),
        ),
    ]
