# Generated by Django 5.2.16 on 2026-09-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_alter_evento_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='punto_encuentro',
            field=models.CharField(help_text='Describe el sitio donde se va a gestionar/concertar la visita.', max_length=255, verbose_name='Punto de encuentro'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('visita', 'Visita'), ('vacacion', 'Vacaciones'), ('cumpleanos', 'Cumpleaños'), ('viaje', 'Viajes'), ('aniversario', 'Aniversarios'), ('boda', 'Bodas'), ('comida_familiar', 'Comida Familiar'), ('graduacion', 'Graduación'), ('bautizo_comunion', 'Bautizo/Comunión'), ('extranjeria', 'Extranjería')], max_length=20, verbose_name='Tipo de evento'),
        ),
    ]
