# Generated by Django 5.2.16 on 2026-08-07 12:58

import django.db.models.deletion
from django.db import migrations, models


def portar_archivos_y_rellenar_grupo(apps, schema_editor):
    """Antes de borrar ArchivoCompartido: copia cada archivo a la biblioteca
    'General' de Canal ALF del grupo de su autor, y rellena Mensaje.grupo
    para los mensajes que ya existían (todo esto ocurría sin distinguir
    grupo, así que se reconstruye a partir del grupo del autor)."""
    Mensaje = apps.get_model('comunicacion', 'Mensaje')
    ArchivoCompartido = apps.get_model('comunicacion', 'ArchivoCompartido')
    Padre = apps.get_model('core', 'Padre')
    GrupoCoparental = apps.get_model('core', 'GrupoCoparental')
    CanalRol = apps.get_model('core', 'CanalRol')
    DocumentoCanal = apps.get_model('core', 'DocumentoCanal')

    def grupo_de(user_id):
        padre = Padre.objects.filter(user_id=user_id).first()
        if padre and padre.grupo_id:
            return padre.grupo_id
        primero = GrupoCoparental.objects.order_by('id').first()
        return primero.id if primero else None

    for mensaje in Mensaje.objects.filter(grupo__isnull=True):
        grupo_id = grupo_de(mensaje.autor_id)
        if grupo_id:
            mensaje.grupo_id = grupo_id
            mensaje.save(update_fields=['grupo'])

    for archivo in ArchivoCompartido.objects.all():
        grupo_id = grupo_de(archivo.autor_id)
        if not grupo_id:
            continue
        canal, _ = CanalRol.objects.get_or_create(grupo_id=grupo_id, rol='general')
        DocumentoCanal.objects.create(
            canal=canal,
            subido_por_id=archivo.autor_id,
            archivo=archivo.archivo.name,
            titulo=archivo.descripcion or archivo.archivo.name,
            descripcion=archivo.descripcion,
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0001_initial'),
        ('core', '0008_alter_canalrol_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_internos', to='core.grupocoparental'),
        ),
        migrations.RunPython(portar_archivos_y_rellenar_grupo, noop),
        migrations.DeleteModel(
            name='ArchivoCompartido',
        ),
    ]
